export enum DPI {
  CASCO = 'CASCO',
  GUANTI = 'GUANTI',
  OCCHIALI = 'OCCHIALI',
  CUFFIE_PROTEZIONE = 'CUFFIE_PROTEZIONE',
  MASCHERA = 'MASCHERA',
  SCARPE_ANTINFORTUNISTICHE = 'SCARPE_ANTINFORTUNISTICHE',
  IMBRACATURA = 'IMBRACATURA',
  DPI_VIE_RESPIRATORIE = 'DPI_VIE_RESPIRATORIE',
  INDUMENTI_PROTETTIVI = 'INDUMENTI_PROTETTIVI',
  ALTRO = 'ALTRO',
}
