export enum RischioLavorativo {
  CADUTA_ALTEZZA = 'CADUTA_ALTEZZA',
  RISCHIO_CHIMICO = 'RISCHIO_CHIMICO',
  RISCHIO_FISICO = 'RISCHIO_FISICO',
  RISCHIO_BIOLOGICO = 'RISCHIO_BIOLOGICO',
  RISCHIO_ERGONOMICO = 'RISCHIO_ERGONOMICO',
  RISCHIO_ELETTRICO = 'RISCHIO_ELETTRICO',
  MOVIMENTAZIONE_CARICHI = 'MOVIMENTAZIONE_CARICHI',
  RISCHIO_INCENDIO = 'RISCHIO_INCENDIO',
  RISCHIO_RUMORE = 'RISCHIO_RUMORE',
  ALTRO = 'ALTRO',
}
