import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';
import { permissionGuard } from './core/guards/permission.guard';

export const routes: Routes = [
  {
    path: 'login',
    loadComponent: () => import('./features/auth/login/login').then((m) => m.Login),
  },
  {
    path: 'forgot-password',
    loadComponent: () => import('./features/auth/forgot-password/forgot-password').then((m) => m.ForgotPassword),
  },
  {
    path: 'reset-password',
    loadComponent: () => import('./features/auth/reset-password/reset-password').then((m) => m.ResetPassword),
  },
  {
    path: 'dashboard',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_DASHBOARD_VIEW'] },
    loadComponent: () => import('./features/dashboard/dashboard').then((m) => m.Dashboard),
  },
  {
    path: 'users',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_USER_VIEW'] },
    loadComponent: () => import('./features/users/users').then((m) => m.Users),
  },
  {
    path: 'users/new',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_USER_CREATE'] },
    loadComponent: () => import('./features/users/user-create-page/user-create-page').then((m) => m.UserCreatePage),
  },
  {
    path: 'users/:id',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_USER_VIEW'] },
    loadComponent: () => import('./features/users/user-detail-page/user-detail-page').then((m) => m.UserDetailPage),
  },
  {
    path: 'users/:id/edit',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_USER_EDIT'] },
    loadComponent: () => import('./features/users/user-edit-page/user-edit-page').then((m) => m.UserEditPage),
  },
  {
    path: 'roles',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_ROLE_VIEW'] },
    loadComponent: () => import('./features/roles/roles').then((m) => m.Roles),
  },
  {
    path: 'roles/new',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_ROLE_CREATE'] },
    loadComponent: () => import('./features/roles/role-create-page/role-create-page').then((m) => m.RoleCreatePage),
  },
  {
    path: 'profiles',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_PERMISSION_VIEW'] },
    loadComponent: () => import('./features/profiles/profiles').then((m) => m.Profiles),
  },
  {
    path: 'profiles/:id/permissions',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['ACTION_ASSIGN_PERMISSION'] },
    loadComponent: () => import('./features/profiles/profile-permissions/profile-permissions').then((m) => m.ProfilePermissions),
  },
  {
    path: 'policies',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_PERMISSION_VIEW'] },
    loadComponent: () => import('./features/policies/policies').then((m) => m.Policies),
  },
  {
    path: 'companies/new',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_COMPANY_CREATE'] },
    loadComponent: () => import('./features/companies/company-create-page/company-create-page').then((m) => m.CompanyCreatePage),
  },
  {
    path: 'companies/:uuid',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_COMPANY_VIEW'] },
    loadComponent: () => import('./features/companies/company-detail-page/company-detail-page').then((m) => m.CompanyDetailPage),
  },
  {
    path: 'companies',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_COMPANY_VIEW'] },
    loadComponent: () => import('./features/companies/companies').then((m) => m.Companies),
  },
  {
    path: 'sedi-operative',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_SEDE_OPERATIVA_VIEW'] },
    loadComponent: () => import('./features/sedi-operative/sedi-operative').then((m) => m.SediOperative),
  },
  {
    path: 'sedi-operative/:companyId/new',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_SEDE_OPERATIVA_CREATE'] },
    loadComponent: () => import('./features/sedi-operative/sede-operativa-create-page/sede-operativa-create-page').then((m) => m.SedeOperativaCreatePage),
  },
  {
    path: 'sedi-operative/:companyId/:id',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_SEDE_OPERATIVA_VIEW'] },
    loadComponent: () => import('./features/sedi-operative/sede-operativa-detail-page/sede-operativa-detail-page').then((m) => m.SedeOperativaDetailPage),
  },
  {
    path: 'sedi-operative/:companyId/:id/edit',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_SEDE_OPERATIVA_EDIT'] },
    loadComponent: () => import('./features/sedi-operative/sede-operativa-edit-page/sede-operativa-edit-page').then((m) => m.SedeOperativaEditPage),
  },
  {
    path: 'mansione',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_MANSIONE_VIEW'] },
    loadComponent: () => import('./features/mansione/mansione').then((m) => m.MansioneList),
  },
  {
    path: 'mansione/new',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_MANSIONE_CREATE'] },
    loadComponent: () => import('./features/mansione/mansione-create-page/mansione-create-page').then((m) => m.MansioneCreatePage),
  },
  {
    path: 'mansione/:id',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_MANSIONE_VIEW'] },
    loadComponent: () => import('./features/mansione/mansione-detail-page/mansione-detail-page').then((m) => m.MansioneDetailPage),
  },
  {
    path: 'mansione/:id/edit',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_MANSIONE_EDIT'] },
    loadComponent: () => import('./features/mansione/mansione-edit-page/mansione-edit-page').then((m) => m.MansioneEditPage),
  },
  {
    path: 'formazione',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_FORMAZIONE_VIEW'] },
    loadComponent: () => import('./features/formazione/formazione').then((m) => m.FormazioneList),
  },
  {
    path: 'formazione/new',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_FORMAZIONE_CREATE'] },
    loadComponent: () => import('./features/formazione/formazione-create-page/formazione-create-page').then((m) => m.FormazioneCreatePage),
  },
  {
    path: 'formazione/:id',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_FORMAZIONE_VIEW'] },
    loadComponent: () => import('./features/formazione/formazione-detail-page/formazione-detail-page').then((m) => m.FormazioneDetailPage),
  },
  {
    path: 'formazione/:id/edit',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_FORMAZIONE_EDIT'] },
    loadComponent: () => import('./features/formazione/formazione-edit-page/formazione-edit-page').then((m) => m.FormazioneEditPage),
  },
  {
    path: 'sorveglianza-sanitaria',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_SORVEGLIANZA_SANITARIA_VIEW'] },
    loadComponent: () => import('./features/sorveglianza-sanitaria/sorveglianza-sanitaria').then((m) => m.SorveglianzaSanitariaList),
  },
  {
    path: 'sorveglianza-sanitaria/new',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_SORVEGLIANZA_SANITARIA_CREATE'] },
    loadComponent: () => import('./features/sorveglianza-sanitaria/sorveglianza-sanitaria-create-page/sorveglianza-sanitaria-create-page').then((m) => m.SorveglianzaSanitariaCreatePage),
  },
  {
    path: 'sorveglianza-sanitaria/:id',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_SORVEGLIANZA_SANITARIA_VIEW'] },
    loadComponent: () => import('./features/sorveglianza-sanitaria/sorveglianza-sanitaria-detail-page/sorveglianza-sanitaria-detail-page').then((m) => m.SorveglianzaSanitariaDetailPage),
  },
  {
    path: 'sorveglianza-sanitaria/:id/edit',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['PAGE_SORVEGLIANZA_SANITARIA_EDIT'] },
    loadComponent: () => import('./features/sorveglianza-sanitaria/sorveglianza-sanitaria-edit-page/sorveglianza-sanitaria-edit-page').then((m) => m.SorveglianzaSanitariaEditPage),
  },
  {
    path: 'company-settings',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['SECTION_COMPANY_SETTINGS', 'PAGE_COMPANY_EDIT'], tenantAccess: true },
    loadComponent: () => import('./features/company-settings/company-settings').then((m) => m.CompanySettingsPage),
  },
  {
    path: 'profile',
    canActivate: [authGuard, permissionGuard],
    data: { permissions: ['SECTION_PROFILE'] },
    loadComponent: () => import('./features/profile/profile').then((m) => m.Profile),
  },
  {
    path: 'forbidden',
    loadComponent: () => import('./features/forbidden/forbidden').then((m) => m.Forbidden),
  },
  { path: '', redirectTo: '/login', pathMatch: 'full' },
  { path: '**', redirectTo: '/login' },
];
